{
  imports = [
    ./aerospace.nix
    ./atuin.nix
    ./bat.nix
    ./bottom.nix
    ./btop.nix
    ./direnv.nix
    ./eza.nix
    ./fastfetch.nix
    ./fd.nix
    ./fish.nix
    ./fzf.nix
    ./gh_cli.nix
    ./ghostty.nix
    ./git.nix
    ./helix.nix
    ./jjui.nix
    ./jq.nix
    ./jujutsu.nix
    ./k9s.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./mise.nix
    ./opencode.nix
    ./pay-respects.nix
    ./ripgrep.nix
    ./scooter.nix
    ./ssh.nix
    ./tools.nix
    ./yazi.nix
    ./zoxide.nix
  ];
}
