{
  imports = [
    ./atuin.nix
    ./1password.nix
    ./helix.nix
    ./fastfetch.nix
    ./fish.nix
    ./ghostty.nix
    ./lazygit.nix
    ./lazydocker.nix
    ./zoxide.nix
    ./eza.nix
    ./pay-respects.nix
    ./git.nix
    ./jujutsu.nix
    ./bat.nix
    ./zen.nix
    ./ssh.nix
    ./spotify.nix
    ./tools.nix
  ];
}
