name: "Validate Flake and push to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  nix-check:
    name: Nix Flake Validation
    runs-on: macos-26-arm
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Check Flake Metadata
        run: nix flake check

      - name: Nix Format Check
        run: nix fmt -- --check .
  flakehub-publish:
    runs-on: macos-26-arm
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-push@main
        with:
          name: drlucaa/nixconfig
          rolling: true
          visibility: public
          include-output-paths: true
